const AllDataProducts = [
  {
    id: 1,
    stock: 5,
    src: [
      "https://i.postimg.cc/htZpFt1s/Reloj-Smartwatch-Amazfit-GTS-2-Mini-40mm-Black-by-XIAOMI-tab-1.png",
    ],
    Title: "Xiaomi Band 8",
    Text: "10' Touch Screen, NFC tecnology, +10 days battery  ",
    Price: 56,
    Warranty: "1 year warranty",
    categoryID: 9,
    Amount: 1,
    category: {
      name: "Digital",
      id: 9,
    },
  },
  {
    id: 2,
    stock: 3,
    src: "https://i.postimg.cc/y88vrZcW/xiaomi-pulsera-de-actividad-mi-band-6.jpg",
    Title: "Amazfit GTS 2 mini",
    Text: "1.56 Touch Screen, GPS, Bluetooth, IOS and Android Compatibility,Water Resistant",
    Price: 76,
    Warranty: "1 year warranty",
    categoryID: 9,
    Amount: 1,
    category: {
      name: "Digital",
      id: 9,
    },
  },
  {
    id: 3,
    stock: 3,
    src: "https://i.postimg.cc/pLrJBtMF/SAN-40-10.jpg",
    Title: "Casio Sport",
    Text: "Water resistant, Classic clock functions, and more",
    Price: 50,
    Warranty: "1 year warranty",
    categoryID: 9,
    Amount: 1,
    category: {
      name: "Digital",
      id: 9,
    },
  },
  {
    id: 4,
    stock: 12,
    src: "https://i.postimg.cc/nhZZbRGm/Saati-Reloj-de-pulsera-Digital-para-hombre-y-mujer-cron-grafo-de-Deportes-de-choque-de.jpg",
    Title: "Casio Vintage",
    Text: "Water Resistant, +7 years battery duration, calendary, sport functions",
    Price: 55,
    categoryID: 8,
    Amount: 1,
    Warranty: "1 year warranty",
    category: {
      name: "Casual",
      id: 8,
    },
  },
  {
    id: 5,
    stock: 10,
    src: "https://i.postimg.cc/Xq24Wg1K/81524n-Ar-Hx-L-UX679.jpg",
    Title: "Brigada Watch",
    Text: "Water Resistant, +5 years battery duration, clasic watch functions, elegant, diferents colors",
    Price: 65,
    Warranty: "1 year warranty",
    categoryID: 8,
    Amount: 1,
    category: {
      name: "Casual",
      id: 8,
    },
  },
  {
    id: 6,
    stock: 8,
    src: "https://i.postimg.cc/90zWNJZ9/gsc-112970503-478261-1.jpg",
    Title: "Casio Casual Movft",
    Text: "One of the most popular watches of the world, mordern, beutiful and it looks perfect on any oufit, water resistant, different colors and you can personalize it.",
    Price: 115,
    Warranty: "1 year warranty",
    categoryID: 8,
    Amount: 1,
    category: {
      name: "Casual",
      id: 8,
    },
  },
  {
    id: 7,
    stock: 8,
    src: "https://i.postimg.cc/4yhF29LP/239301-945b7866c4aba5f68415915838384306-1024-1024.png",
    Title: "Paddle Watch",
    Text: "Classic Watch, Elegant and with the clasic watch functions.",
    Price: 80,
    Warranty: "1 year warranty",
    categoryID: 8,
    Amount: 1,
    category: {
      name: "Casual",
      id: 8,
    },
  },
  {
    id: 8,
    stock: 3,
    src: "https://i.postimg.cc/brNF85w6/Aeternitas-3.png",
    Title: "Aeternitas 3",
    Text: "Luxury Watch, One of the most exclusive watches in our company, diamond-watch",
    Price: 35000,
    Warranty: "3 year warranty",
    categoryID: 7,
    Amount: 1,
    category: {
      name: "Luxury",
      id: 7,
    },
  },
  {
    id: 9,
    stock: 5,
    src: "https://i.postimg.cc/SNdRD6yG/6ddbbd47da5bc4b5c16863512eb40ae9.jpg",
    Title: "Patek Philippe Nautilus",
    Text: `Patek Philippe Nautilus 5711/1A-010  Stainless Steel Black-blue Dial 43mm x 38mm stainless steel case, sapphire crystal back, screw-down crown, black-blue dial with gold applied hour markers with luminescent coating, self-winding caliber 324 S C movement with date and sweep second hand, approximately 45 hour of power reserve, stainless steel bracelet. Water resistant to 120 meters.`,
    Price: 20000,
    Warranty: "3 year warranty",
    categoryID: 7,
    Amount: 1,
    category: {
      name: "Luxury",
      id: 7,
    },
  },
  {
    id: 10,
    stock: 2,
    src: "https://i.postimg.cc/G2jSWRd8/day-date-40-m228239-0033-search.webp",
    Title: "Rolex Day-Date",
    Text: "Rolex Day-Date 40 228349RBR men's watch. Features a polished solid 18k white gold case and brushed with polished solid 18k white gold President bracelet. Polished solid 18k white gold fixed diamond bezel. Silver dial with Roma numeral and index hour markers. Date window displayed under cyclops lens at 3 o'clock. Day window displayed at 12 o'clock. Instantaneous day and date setting, and more.",
    Price: 61000,
    Warranty: "3 year warranty",
    categoryID: 7,
    Amount: 1,
    category: {
      name: "Luxury",
      id: 7,
    },
  },
  {
    id: 11,
    stock: 3,
    src: "https://i.postimg.cc/bYF5XJzf/m126233-0039-modelpage-flagship-1.jpg",
    Title: "Rolex Olyster",
    Text: "The Rolex Datejust 36mm M116233-0150 is an authentic Swiss-made Men’s or Women’s luxury watch which features a polished 904L Oystersteel stainless steel case with screw down crown and case back. The two tone polished solid 18k yellow gold with brushed 904L Oystersteel stainless steel jubilee bracelet has a concealed folding crownclasp deployment buckle. A champagne dial is adorned with 10 diamond hour markers and a date aperture at the 3 o’clock position encompassed in polished solid 18k yellow gold fluted bezel. This eye-catching watch is driven by Self-winding automatic movement and a 48 hour power reserve.",
    Price: 71000,
    Warranty: "3 year warranty",
    categoryID: 7,
    Amount: 1,
    category: {
      name: "Luxury",
      id: 7,
    },
  },
  {
    id: 12,
    stock: 12,
    src: "https://i.postimg.cc/15S409qw/reloj-tommy-hilfiger-hombre-1791.jpg",
    Title: "Tommy Watch",
    Text: "The Tommy Hilfiger Hendrix watch is a casual watch with minimalist inspiration. It has a sleek 43mm steel case and features a smooth textured finish dial that perfectly matches the woven steel mesh. It has a water resistance of 5 ATM / 50 meters.",
    Price: 21000,
    Warranty: "3 year warranty",
    categoryID: 7,
    Amount: 1,
    category: {
      name: "Luxury",
      id: 7,
    },
  },
];


export default AllDataProducts;
